services:

  postgres:
    image: postgres:16
    container_name: autoops-postgres

    environment:
      POSTGRES_DB: autoops
      POSTGRES_USER: autoops
      POSTGRES_PASSWORD: autoops

    ports:
      - "5432:5432"

    volumes:
      - autoops_postgres_data:/var/lib/postgresql/data

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U autoops -d autoops"
        ]
      interval: 5s
      timeout: 5s
      retries: 10


  redis:
    image: redis:8-alpine
    container_name: autoops-redis

    ports:
      - "6379:6379"

    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 10

  backend:
    build:
      context: ./backend

    container_name: autoops-backend

    environment:
      DB_URL: "jdbc:postgresql://postgres:5432/autoops"
      DB_USER: "autoops"
      DB_PASSWORD: "autoops"

      SPRING_DATA_REDIS_HOST: "redis"
      SPRING_DATA_REDIS_PORT: "6379"

    ports:
      - "8080:8080"

    depends_on:
      postgres:
        condition: service_healthy

      redis:
        condition: service_healthy

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -fsS http://localhost:8080/actuator/health || exit 1"
        ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  frontend:
    build:
      context: ./frontend

    container_name: autoops-frontend

    ports:
      - "80:80"

    depends_on:
      backend:
        condition: service_healthy

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -fsS http://localhost/ || exit 1"
        ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

volumes:
  autoops_postgres_data: