import { useState } from 'react'
import { useQuery } from '@tanstack/react-query'

import { getJobLogs } from '../api/jobLogsApi'
import type {
  JobLog,
  JobLogLevel,
} from '../types'
import { getApiErrorMessage } from '../api/apiError'

type LogLevelFilter = 'ALL' | JobLogLevel

const levelClasses: Record<
  JobLogLevel,
  string
> = {
  INFO:
    'bg-blue-50 text-blue-700 ring-blue-600/20',

  WARN:
    'bg-amber-50 text-amber-700 ring-amber-600/20',

  ERROR:
    'bg-red-50 text-red-700 ring-red-600/20',
}

const formatDate = (
  value: string,
) => {
  return new Date(value).toLocaleString()
}

const formatJobType = (
  type: JobLog['jobType'],
) => {
  switch (type) {
    case 'HEALTH_CHECK':
      return 'Health Check'

    case 'RESTART_SERVICE':
      return 'Restart Service'

    default:
      return type
  }
}

const LogsPage = () => {
  const [searchTerm, setSearchTerm] =
    useState('')

  const [level, setLevel] =
    useState<LogLevelFilter>('ALL')

  const {
    data: logs = [],
    isLoading,
    isError,
    error,
  } = useQuery({
    queryKey: ['job-logs'],
    queryFn: getJobLogs,
  })

  const filteredLogs =
    logs.filter((log) => {
      const normalizedSearch =
        searchTerm
          .trim()
          .toLowerCase()

      const matchesSearch =
        normalizedSearch === '' ||
        log.serviceName
          .toLowerCase()
          .includes(normalizedSearch) ||
        log.message
          .toLowerCase()
          .includes(normalizedSearch) ||
        log.jobType
          .toLowerCase()
          .includes(normalizedSearch)

      const matchesLevel =
        level === 'ALL' ||
        log.level === level

      return (
        matchesSearch &&
        matchesLevel
      )
    })

  const handleClearFilters = () => {
    setSearchTerm('')
    setLevel('ALL')
  }

  return (
    <main className="p-4 sm:p-6 lg:p-8">
      <header>
        <h1 className="text-2xl font-bold text-slate-900 sm:text-3xl">
          Logs
        </h1>

        <p className="mt-2 text-slate-600">
          Inspect technical execution logs
          generated by operational jobs.
        </p>
      </header>

      <section className="mt-8 rounded-xl border border-slate-200 bg-white p-4 shadow-sm">
        <div className="grid gap-4 md:grid-cols-3">
          <div className="md:col-span-2">
            <label
              htmlFor="log-search"
              className="mb-2 block text-sm font-medium text-slate-700"
            >
              Search
            </label>

            <input
              id="log-search"
              type="text"
              value={searchTerm}
              onChange={(event) =>
                setSearchTerm(
                  event.target.value,
                )
              }
              placeholder="Search service, job type, or message..."
              className="w-full rounded-lg border border-slate-300 px-3 py-2 text-sm outline-none focus:border-slate-500"
            />
          </div>

          <div>
            <label
              htmlFor="log-level-filter"
              className="mb-2 block text-sm font-medium text-slate-700"
            >
              Level
            </label>

            <select
              id="log-level-filter"
              value={level}
              onChange={(event) =>
                setLevel(
                  event.target
                    .value as LogLevelFilter,
                )
              }
              className="w-full rounded-lg border border-slate-300 bg-white px-3 py-2 text-sm"
            >
              <option value="ALL">
                All
              </option>

              <option value="INFO">
                Info
              </option>

              <option value="WARN">
                Warning
              </option>

              <option value="ERROR">
                Error
              </option>
            </select>
          </div>
        </div>

        <div className="mt-4 flex items-center justify-between">
          <p className="text-sm text-slate-500">
            Showing{' '}
            {filteredLogs.length} of{' '}
            {logs.length} logs
          </p>

          <button
            type="button"
            onClick={handleClearFilters}
            className="text-sm font-medium text-slate-600 hover:text-slate-900"
          >
            Clear filters
          </button>
        </div>
      </section>

      <section className="mt-6">
        {isLoading && (
          <div className="rounded-xl border border-slate-200 bg-white p-8 text-center">
            <p className="text-sm text-slate-500">
              Loading logs...
            </p>
          </div>
        )}

        {isError && (
          <div className="rounded-xl border border-red-200 bg-red-50 p-8 text-center">
            <p className="text-sm text-red-700">
              {getApiErrorMessage(error)}
            </p>
          </div>
        )}

        {!isLoading &&
          !isError &&
          filteredLogs.length === 0 && (
            <div className="rounded-xl border border-slate-200 bg-white p-8 text-center">
              <h2 className="font-semibold text-slate-900">
                No logs found
              </h2>

              <p className="mt-2 text-sm text-slate-500">
                Run a health check or adjust
                your filters.
              </p>
            </div>
          )}

        {!isLoading &&
          !isError &&
          filteredLogs.length > 0 && (
            <div className="overflow-hidden rounded-xl border border-slate-200 bg-white shadow-sm">
              <div className="overflow-x-auto">
                <table className="w-full min-w-[950px] text-left">
                  <thead className="border-b border-slate-200 bg-slate-50">
                    <tr>
                      <th className="px-6 py-4 text-xs font-semibold uppercase tracking-wide text-slate-500">
                        Time
                      </th>

                      <th className="px-6 py-4 text-xs font-semibold uppercase tracking-wide text-slate-500">
                        Service
                      </th>

                      <th className="px-6 py-4 text-xs font-semibold uppercase tracking-wide text-slate-500">
                        Job
                      </th>

                      <th className="px-6 py-4 text-xs font-semibold uppercase tracking-wide text-slate-500">
                        Level
                      </th>

                      <th className="px-6 py-4 text-xs font-semibold uppercase tracking-wide text-slate-500">
                        Message
                      </th>
                    </tr>
                  </thead>

                  <tbody className="divide-y divide-slate-100">
                    {filteredLogs.map(
                      (log) => (
                        <tr
                          key={log.id}
                          className="hover:bg-slate-50"
                        >
                          <td className="whitespace-nowrap px-6 py-4 text-sm text-slate-600">
                            {formatDate(
                              log.createdAt,
                            )}
                          </td>

                          <td className="px-6 py-4">
                            <p className="font-medium text-slate-900">
                              {
                                log.serviceName
                              }
                            </p>

                            <p className="mt-1 text-xs text-slate-500">
                              Service #
                              {log.serviceId}
                            </p>
                          </td>

                          <td className="px-6 py-4">
                            <p className="text-sm text-slate-700">
                              {formatJobType(
                                log.jobType,
                              )}
                            </p>

                            <p className="mt-1 text-xs text-slate-500">
                              Job #
                              {log.jobId}
                            </p>
                          </td>

                          <td className="px-6 py-4">
                            <span
                              className={`inline-flex rounded-full px-2.5 py-1 text-xs font-medium ring-1 ring-inset ${levelClasses[log.level]}`}
                            >
                              {log.level}
                            </span>
                          </td>

                          <td className="max-w-xl px-6 py-4 text-sm text-slate-600">
                            {
                              log.message
                            }
                          </td>
                        </tr>
                      ),
                    )}
                  </tbody>
                </table>
              </div>
            </div>
          )}
      </section>
    </main>
  )
}

export default LogsPage